apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: ouchi-hub-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ouchi-hub-frontend
  template:
    metadata:
      labels:
        app: ouchi-hub-frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
