apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ouchi-hub-frontend
  labels:
    app: frontend-app
    name: ouchi-hub-frontend
spec:
  selector:
    app: ouchi-hub-frontend
  type: NodePort
  ports:
    - name: frontend-port
      port: 80
