apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  labels:
    app: frontend-app
    name: frontend
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: frontend-port
      port: 80
