apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  labels:
    app: frontend-app
    name: frontend
spec:
  type: NodePort
  ports:
    - name: frontend-port
      port: 80
      targetPort: 10081
      protocol: TCP
  selector:
    app: frontend
