apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: ouchi-hub-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ouchi-hub-backend
  template:
    metadata:
      labels:
        app: ouchi-hub-backend
    spec:
      containers:
        - name: ouchi-hub-backend
          image: asia-northeast1-docker.pkg.dev/ouchihub/ouchi-hub/backend:88a2225a3e46f3569a0a9939f29cd38582d593c0
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: ouchihub-storage
              mountPath: /data
          envFrom:
            - configMapRef:
                name: ouchi-hub-backend-config
      imagePullSecrets:
        - name: ouchi-hub-backend-registry-key
      volumes:
        - name: ouchihub-storage
          persistentVolumeClaim:
            claimName: ouchihub-pvc
