apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-northeast1-docker.pkg.dev/ouchihub/ouchi-hub/backend:22ebae50e33c650cecbfdefd2e62014ce059fc28
          ports:
            - containerPort: 9000
      imagePullSecrets:
        - name: ouchi-hub-registry-key
