apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asia-northeast1-docker.pkg.dev/ouchihub/ouchi-hub/backend:a3d0d4e91589c544567f7778e33eb6773806e23f
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ouchi-hub-registry-key
