apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
  labels:
    app: backend-app
    name: backend
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - name: backend-port
      port: 9000
