apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
  labels:
    app: backend-app
    name: backend
spec:
  type: NodePort
  ports:
    - name: backend-port
      port: 80
      targetPort: 10080
      protocol: TCP
  selector:
    app: backend
