apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ouchi-hub-backend
  labels:
    app: backend-app
    name: ouchi-hub-backend
spec:
  selector:
    app: ouchi-hub-backend
  type: NodePort
  ports:
    - name: backend-port
      port: 9000
