apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
  labels:
    app: backend-app
    name: backend
spec:
  type: LoadBalancer
  ports:
    - name: backend-port
      port: 10080
      targetPort: 80
      nodePort: 30080
      protocol: TCP
  selector:
    app: backend
