apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: ouchi-hub-bff
  labels:
    app: bff-app
    name: ouchi-hub-bff
spec:
  selector:
    app: ouchi-hub-bff
  type: NodePort
  ports:
    - name: bff-port
      port: 8080
