apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: bff
  labels:
    app: bff-app
    name: bff
spec:
  selector:
    app: bff
  type: NodePort
  ports:
    - name: bff-port
      port: 8080
