apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ouchi-hub-bff
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akimoto-junya/ouchi-hub-manifests.git
    targetRevision: main
    path: bff
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
