apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
spec:
  project: default
  source:
    repoURL: https://github.com/akimoto-junya/ouchi-hub-manifests.git
    targetRevision: main
    path: frontend
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
